#!/usr/bin/env bash

re="^[-0-9]+(\.[0-9]+)* [-,+,*,/,^] [-0-9\]+(\.[0-9]+)*$"
echo "Welcome to the basic calculator!"
echo "Welcome to the basic calculator!" >> operation_history.txt


while true; do
    echo "Enter an arithmetic operation or type 'quit' to quit:"
    echo "Enter an arithmetic operation or type 'quit' to quit:" >> operation_history.txt
    read input 
    $input >> operation_history.txt
    if [[ "$input" =~ $re ]]; then
        echo "scale=2; $input" | bc -l
        echo "scale=2; $input" | bc -l >> operation_history.txt
        continue;
    elif [[ $input = "quit" ]]; then
        echo "Goodbye!"
        echo "Goodbye!" >> operation_history.txt
        break;
    else
        echo "Operation check failed!"
        echo "Operation check failed!" >> operation_history.txt
        continue;
    fi
done
cat operation_history.txt
